version: "3"
services:

  jupyter:
    build:
      context: ./jupyter
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
          - "./notebooks:/notebooks" 
          - "./data:/data"