server:
  port: 9003
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  datasource:
    url: url
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


surprise:
  auth:
    jwt:
      header: Authorization
      tokenPrefix: "Bearer "
      tokenPrefixSize: 7
      accessTokenValidityInMins: 5
      refreshTokenValidityInDays: 30
      secret: secret
      rolePrefix: ROLE_
    token:
      cleanup-frequency-cron-expression: "0 0 9 30 * ?" #At 09:00:00am, on the 30th day, every month

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.: info
    org.apache.http: info
