server:
  port: 9000
  servlet:
    context-path: /auth

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mysql://localhost:3306/surprise?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: example_user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
