server:
  port: 9000
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/surprise?currentSchema=auth
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


surprise:
  auth:
    jwt:
      header: Authorization
      tokenPrefix: "Bearer "
      tokenPrefixSize: 7
      accessTokenValidityInMins: 5
      refreshTokenValidityInDays: 30
      secret: lrTnWakwCNZlDo0i5l5xkngtQMN0zMle4PJpyl1cHkh8qXbKUblayqB7w2WfARi
      rolePrefix: ROLE_
    token:
      cleanup-frequency-cron-expression: "0 0 9 30 * ?" #At 09:00:00am, on the 30th day, every month

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.: info
    org.apache.http: info
