server:
  port: 9001
  servlet:
    context-path: /users

spring:
  application:
    name: user-service
  datasource:
    url: url
    username: username
    password: username
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      debug: true
  messages:
    basename: i18n/messages

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


surprise:
  auth:
    jwt:
      header: Authorization
      tokenPrefix: "Bearer "
      expiration: 86400000
      secret: secret
      rolePrefix: ROLE_
    users:
      cleanup-frequency-cron-expression: "0 0 1 * * ?" #At 01:00:00am every day
  mail:
    base-url: http://127.0.0.1:8080

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.: info
    org.apache.http: info




