version: '3.1'
services:

  database:
    image: postgres:12.1
    restart: always
    container_name: surprise-db
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: surprise
    ports:
      - 5432:5432
volumes:
  postgres:

